### ISSUE TITLE
Error when running train.py

### ISSUE THREAD

**Issue by simon-minami** [CEA-LIST/KaliCalib#2]
Hello,

I followed the instructions given in the challenge repository to set up the data. However, when I run train.py, I get the following error output:

  0%|          | 0/240 [00:00<?, ?it/s]
  0%|          | 0/240 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/sminam01/bball-tracking/KaliCalib/kalicalib/train.py", line 90, in <module>
    train(cfg)
  File "/sminam01/bball-tracking/KaliCalib/kalicalib/train.py", line 54, in train
    for imgs, data in pbar:
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/sminam01/bball-tracking/KaliCalib/data/datasets/viewds.py", line 315, in __getitem__
    item = self.vds.dataset.query_item(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/aleatorpy/pseudo_random.py", line 70, in __call__
    result = self.f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/deepsport_utilities/utils.py", line 30, in query_item
    item = self.parent.query_item(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/mlworkflow/datasets.py", line 250, in query_item
    item = transform(key, item)
           ^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/bball-tracking/KaliCalib/data/datasets/viewds.py", line 474, in __call__
    item = self._apply_transform_once(key, item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/bball-tracking/KaliCalib/data/datasets/viewds.py", line 444, in _apply_transform_once
    parameters = self._get_current_parameters(key, item)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/deepsport_utilities/ds/instants_dataset/views_transforms.py", line 181, in _get_current_parameters
    size = float(view.calib.compute_length2D(100, keypoints))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/sminam01/condaenv/Pipeline/lib/python3.12/site-packages/calib3d/calib.py", line 358, in compute_length2D
    assert np.isscalar(length3D), f"This function expects a scalar `length3D` argument. Received {length3D}"
AssertionError: This function expects a scalar `length3D` argument. Received [[338.5422839 ]
 [857.10081456]
 [  0.        ]]


Any help would be appreciated! Thanks.

**Comment by tppqt** [comment]
calib3d==2.5.1
